import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#162529",
    paddingLeft: 24,
    paddingRight: 24,
  },
  bodyContainer: {
    flex: 1,
    marginTop: 43,
  },
  plusContainer: {
    alignItems: "flex-end",
    marginTop: 16,
  },
  bg: {
    // width: "100%",
    height: 164,
    // flex: 0.75,
    borderRadius: 16,
    marginBottom: 17,
    marginTop: 16,
  },
  transparentView: {
    flex: 1,
    backgroundColor: "black",
    opacity: 0.78,
    borderRadius: 10,
    // alignItems: "center",
    paddingHorizontal: 12,
  },
  clickableView: {
    flex: 1,
    // alignItems: "center",
    marginTop: 12,
  },
  cardTitle: {
    fontFamily: "medium",
    fontSize: 18,
    color: "#FFF",
    lineHeight: 18,
  },
  cardDesp: {
    width: "70%",
    fontFamily: "medium",
    fontSize: 18,
    color: "#FFF",
    // textAlign: "center",
    marginTop: 8,
    lineHeight: 20,
  },
  avatarContainer: {},
  avatar: {
    height: 45,
    width: 45,
    borderRadius: 117,
  },
  expLevel: {
    fontFamily: "medium",
    fontSize: 18,
    color: "#D5FF45",
    lineHeight: 18,
  },
  inputField: {
    height: 64,
    // backgroundColor: "red",
    borderRadius: 16,
    borderColor: "#636363",
    borderWidth: 1,
    justifyContent: "center",
    marginBottom: 19,
    marginTop: 24,
  },
  inputFieldText: {
    fontFamily: "medium",
    fontSize: 16,
    color: "#EEE",
    // marginLeft: 12,
  },
  doneBtnContainer: {
    alignItems: "flex-end",
  },
  doneBtn: {
    backgroundColor: "#01669E",
    borderRadius: 5,
    width: 60,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  done: {
    fontFamily: "bold",
    fontSize: 12,
    color: "#FFFFFF",
  },
  title: {
    fontFamily: "medium",
    fontSize: 32,
    color: "#EEE",
    marginTop: 16,
  },
  input: {
    color: "#8F8F93",
    fontSize: 24,
    fontFamily: "medium",
    marginLeft: 25,
  },
  date: {
    height: 64,
    width: "45%",
    borderRadius: 16,
    borderColor: "#636363",
    borderWidth: 1,
    justifyContent: "center",
    marginBottom: 19,
    // marginTop: 24,
    paddingHorizontal: 16,
  },
  time: {
    height: 64,
    width: "45%",

    borderRadius: 16,
    borderColor: "#636363",
    borderWidth: 1,
    justifyContent: "center",
    marginBottom: 19,
    // marginTop: 24,
    paddingHorizontal: 16,
  },
  continueBtn: {
    height: 55,
    backgroundColor: "#D5FF45",
    borderRadius: 16,
    marginTop: 6,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 48,
  },
  continueBtnText: {
    fontFamily: "semiBold",
    color: "#000",
    fontSize: 18,
  },
  mainView: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 24,
    flex: 1,
  },
});
export default styles;
